apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secret
  namespace: fcc
type: Opaque
stringData:
  client-id: oauth2-proxy
  client-secret: ULg219wThV+UaRLPfI5xIEvdx4zE41EoZUTGNbgw4o0=
  cookie-secret: AjZFqnaxHwxDw0lP6nnv6oXbNzM3IytgmcOsvEKx5nI=

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: fcc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
          args:
            # --- Core ---
            - --provider=oidc
            - --oidc-issuer-url=https://oauth.service.ferreiracodecraft.com.br
            - --redirect-url=https://oauth2-proxy.service.ferreiracodecraft.com.br/oauth2/callback

            # --- Client ---
            - --client-id=$(OAUTH2_PROXY_CLIENT_ID)
            - --client-secret=$(OAUTH2_PROXY_CLIENT_SECRET)

            # --- Session ---
            - --cookie-domain=.service.ferreiracodecraft.com.br
            - --cookie-secret=$(OAUTH2_PROXY_COOKIE_SECRET)
            - --cookie-secure=true
            - --cookie-httponly=true
            - --cookie-samesite=lax

            - --whitelist-domain=.service.ferreiracodecraft.com.br

            - --set-authorization-header=true
            - --pass-access-token=true

            - --oidc-email-claim=email
            - --oidc-groups-claim=roles


            # --- Access ---
            - --email-domain=*
            - --scope=openid profile email

            # --- UX ---
            - --upstream=static://200
            - --http-address=0.0.0.0:4180

          env:
            - name: OAUTH2_PROXY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy-secret
                  key: client-id
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy-secret
                  key: client-secret
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy-secret
                  key: cookie-secret

          ports:
            - containerPort: 4180

---

apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy-service
  namespace: fcc
spec:
  type: ClusterIP
  selector:
    app: oauth2-proxy
  ports:
    - port: 80
      targetPort: 4180

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2-proxy-ingress
  namespace: fcc
  annotations:
    cert-manager.io/issuer: letsencrypt-issuer
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - oauth2-proxy.service.ferreiracodecraft.com.br
      secretName: oauth2-proxy-tls
  rules:
    - host: oauth2-proxy.service.ferreiracodecraft.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: oauth2-proxy-service
                port:
                  number: 80

