name: CI/CD Kubernetes ...

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: fcc_environments

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_B64 }}" | base64 -d > kubeconfig
          echo "KUBECONFIG=$(pwd)/kubeconfig" >> $GITHUB_ENV

      - name: Aplicar manifests no cluster
        run: |
          kubectl apply -f k8s/
          kubectl rollout status deployment/oauth2-proxy -n fcc
